language: ruby
sudo: false
before_install:
  - gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
  include:
    - rvm: 2.1.1
    - rvm: 2.2.6
    - rvm: 2.3.5
    - rvm: 2.4.2
    - rvm: 2.5.0
    - rvm: ruby-head